### PR TITLE
USA specific changes for Plat Eng

### PR DESCRIPTION
**Pull request by aochsner**

### CODE REVIEW

**Comment by spotted-dog** [comment]
Looks good to me.

**Review by mathomas — APPROVED** [review]
Looks good to me, too.

**Comment by aochsner** [comment]
@hoagrawal just an FYI that we're updating the US PE job descriptions a bit.  Think it's OK if these diverge (they probably need to tuned to your local market anyways) but wanted you just to be aware.

**Comment by hoagrawal** [comment]
@aochsner thanks for info. Yes, it is good idea. I like that, we may at some point also add India specific directory.

**Pull request merged**
