### PR TITLE
Add tech exercises

### PR DESCRIPTION
**Pull request by panosvoudouris**
Since the job specs are here should we not add the tech exercises too? I think it would be a good idea to have them all in github. We can then link from the website and people could read the job specs, find the relevant exercise and then submit their solution (maybe as a fork with pull request...?).

I have added the tech exercises as they are now from Confluence.

### CODE REVIEW

**Comment by keithmadsen** [comment]
Good question, it certainly would add more transparency to the process. Are the exercises something that we want in the public domain though?

**Comment by luciocodeghini** [comment]
I was just wondering the same thing @keithmadsen... I don't mind the org stuff being public, but the tech exercises not so much tbh (for now)

**Comment by panosvoudouris** [comment]
What issue would we hit if the exercise is public? Perhaps I'm seeing this from a slightly different point of view, we are now doing pair programming building on the tech submission when interviewing front end devs. So any plagiarism or other such things should become apparent very quickly...?

**Comment by keithmadsen** [comment]
I think that it would be better to limit the potential for plagiarism before applicants get as far as the PP stage?

Also, what's to stop people who haven't passed the screening from submitting solutions?

If the exercises are to be public though, we would need to publish the entire process so that applicants know what they're in for.

**Comment by luciocodeghini** [comment]
@panosvoudouris you have a point about the follow-up pairing - it does change things. I still have a few questions, but perhaps water cooler material...

**Comment by panosvoudouris** [comment]
If ppl are ok then I'll merge? Speak now or forever hold your peace (well sometime before Monday afternoon).

**Pull request merged**
