### PR TITLE
Rename to add ordering and align with role names

### PR DESCRIPTION
**Pull request by simoncopsey**
Renaming of files to:
1. Reflect latest general view on role names
2. Add ordering to allow easier collation of JDs (via numbering suffix)

### CODE REVIEW

**Comment by panosvoudouris** [comment]
Is the Our Clients file part of the sequence?

**Comment by simoncopsey** [comment]
Good question. I don't think it's currently used (based README.md and Buildit Job Spec Template.docx), but I'm behind on context.

@ncantor - are you aware of the intention for 'our_clients_eng.md'; is it still required? Thanks!

**Comment by ncantor** [comment]
It's not part of the sequence, at the moment. I started writing it because we thought that giving a view of what our clients needed might be beneficial for the job spec. I'm not sure it is, any longer, as I think we cover a lot in the main why_would_you_join_us section.

**Comment by panosvoudouris** [comment]
Ok cool, so I suppose we can remove it then. If we then rename/merge this stuff I'd be keen to share the job specs with a new recruiter we'll be getting on board soon. Would be interesting to see if we get any interesting comments from their candidates vs the current job specs.

**Comment by simoncopsey** [comment]
Thanks @panosvoudouris @ncantor. I'll merge this in and work with @yannislionis to distribute internally and to existing recruiters. @panosvoudouris - fan of your idea of getting fresh eyes and comments.

**Pull request merged**
